services:
  frontend:
    image: julianahaddad/idata-frontend:v4
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - idata-network
  backend:
    image: julianahaddad/idata-backend:v4
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - idata-network
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - idata-network
networks:
  idata-network:
    driver: bridge