# Arquivos do sistema
*.log
*.dat
NTUSER*
ntuser*

# Diretórios do usuário
VirtualBox/
AppData/
Downloads/
Documents/
Pictures/
Videos/
Music/
Favorites/
Links/
Searches/
Cookies/
Configuracoes Locais/
Ambiente de Impressao/
Ambiente de Rede/
Menu Iniciar/
Meus Documentos/
Modelos/
Recent/
SendTo/

# Arquivos de configuração
.bash_history
.bash_profile
.bashrc
.gitconfig
.angular-config.json
.lesshst

# Ferramentas e caches
.cache/
.config/
.docker/
.dotnet/
.eclipse/
.expo/
.gradle/
.ipython/
.jupyter/
.lemminx/
.m2/
.nuget/
.p2/
.packettracer
.redhat/
.rest-client/
.sonarlint/
.sts4/
.vscode/

# Projetos e arquivos temporários
AngulasProjects/
Cisco Packet Tracer 8.2.2/
ProjetoJava/
P1_PW/
PBI/
Treinamento Smart Consulting/
VirtualBox VMs/
VisualStudioSetup.exe
cadastro-usuarios-main.zip
cadastro-usuarios-main/
eclipse-inst-jre-win64.exe

# Docker
docker-compose.override.yml

# Backend
backend/idata/target/
backend/idata/.mvn/
backend/idata/mvnw
backend/idata/mvnw.cmd

# Frontend
frontend/node_modules/
frontend/dist/
frontend/.angular/