version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --quiet

  backend:
    image: julianahaddad/idata-backend:v3
    container_name: idata-backend
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/idata

  frontend:
    build: ./frontend
    container_name: idata-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data: